# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e474c32c5f6a1a3af23917f99643d49e5a86c5d427e391bccc97d310e03357771c4debe51dd044adf8be8f3bd5efe7678b078abddf1ae0953d3d89dd08d1938

test:
  secret_key_base: d345047da7f029f0361153e1ecd3d961849a0560ebad8fddb5cf0816b133651416c2bf7d8e0df58b7d3de778867db8a5f93b18d45bf6b56f965c80de7cf0d0d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
